#-------------------------------
# General Site Settings
menu:
- { name: 'mccrmck',  url: ''}
- { name: 'calendar',  url: 'calendar'}
- { name: 'catalogue', url: 'catalogue' }
- { name: 'reach', url: 'reach' }
- { name: 'musings', url: 'musings'}
- { name: 'collaborators',   url: 'collaborators' }
- { name: 'kwalifikayshuns', url: 'cv' }

#-------------------------------
# catalogue
catalogue:
  #- {path: , url,} Henriette's new record
  #- {path: , url,} noe goy paa M
- {path: 'graosido.jpg' , url: 'https://knutkviftenesheim.bandcamp.com/album/graosido' } # 05.23
- {path: 'eatRich.jpg' , url: '' } # 06.22
- {path: 'mensa.jpg' , url: 'https://ojkos.bandcamp.com/album/mensa-rotunda' } # 0.5.22
- {path: 'materialism.jpg' , url: '' } # 02.22
- {path: 'johannescamilla.jpg' , url: 'https://johannesfossesolvangcamillahole.bandcamp.com/album/miniatyrland' } # 12.21
- {path: 'flute.jpg' , url: 'https://henrietteeilertsen.bandcamp.com/album/poems-for-flute' } # 09.21
- {path: 'alea.jpg' , url: 'https://ojkos.bandcamp.com/album/alea-iacta-est' } # 05.20
- {path: 'nethuns.jpg' , url: 'https://dugnadrec.bandcamp.com/album/nethuns-music-for-14-piece-ensemble' } # 03.20
- {path: 'proxemicsI.jpg' , url: '' } # 02.20
- {path: 'pep.jpg' , url: '' } # 11.18
- {path: 'frost.jpg' , url: 'https://mccrmck.bandcamp.com/album/first-frost' } # 05.18
# - {path: 'solotet.jpg' , url: '' }
#-------------------------------
# Projects Section

projects:
- {name: 'acousmatic', url: 'eam'}
- {name: 'NSFW', url: 'nsfw'}
- {name: 'proxemics', url: 'proxemics'}
- {name: 'under: went',  url: 'underwent'}
- {name: 'YAWN',  url: 'yawn'}

#-------------------------------
# Footer

social:
- {icon: 'bandcamp',  link: 'https://mccrmck.bandcamp.com'}
- {icon: 'github',    link: 'https://github.com/mccrmck'}
- {icon: 'youtube',   link: 'https://www.youtube.com/@mccrmck_' }

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Mike McCormick'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
